; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.27"

; Modules
projects[simplesamlphp_auth][subdir] = "contrib"
projects[simplesamlphp_auth][version] = "2.0-alpha2"
